services:
  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    restart: on-failure
    container_name: nodejs-backend
    volumes:
      - node-modules:/app/node_modules
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: on-failure
    container_name: mongodb
    ports:
      - '${MONGO_DB_PORT}:${MONGO_DB_PORT_DEFAULT}'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app-network

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure
    container_name: react-frontend
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build && tail -f /dev/null"
    networks:
      - app-network
    depends_on:
      - nodejs

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: on-failure
    container_name: nginx-proxy
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
      - '${NGINX_SSL_PORT}:${NGINX_SSL_PORT}'
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx/configs/default.conf:/etc/nginx/default.conf:ro
    networks:
      - app-network
    depends_on:
      - nodejs
      - react

volumes:
  mongo-data:
    name: mongo-data
  node-modules:
    name: node-modules

networks:
  app-network:
    driver: bridge
