worker_processes auto;
error_log /var/log/nginx/error.log;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 8080;
        server_name _;

        allow 127.0.0.1;
        allow ::1;
        allow ${ALLOWED_IP}
        deny all;

        location / {
            root /backups;
            autoindex on;
            try_files $uri $uri/ =404;
        }

        location ~ /\. {
            deny all;
        }
    }

}
